# Site settings
title: Clean
email: mylittleswift@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My GitHub Resume
baseurl: "/mylittleswift.github.io" # the subpath of your site, e.g. /blog/
url: "https://github.com/Mylittleswift" # the base hostname & protocol for your site
twitter_username: mylittleswift
github_username:  mylittleswift

# Build settings
markdown: kramdown
